# Control Types Enum
uint8 JOINT_POSITION = 0
uint8 JOINT_IMPEDANCE = 1
uint8 CARTESIAN_POSITION = 2
uint8 CARTESIAN_IMPEDANCE = 3
uint8 GRAVITY_COMPENSATION = 4
uint8 JOINT_GROUP_POSITION = 5

string part_name          # "torso", "right_arm", "left_arm", "head"
uint8 control_type        # 위 Enum 값 중 하나

# 공용 제어 파라미터 (모두 전송받되, C++ 로직 내에서 control_type에 따라 선별 사용)
string ref_link
string target_link
float64[] translation_weight
float64[] rotation_weight
float64[] joint_stiffness
float64 damping_ratio
float64 linear_velocity_limit
float64 angular_velocity_limit
string[] joint_names      # JointGroupPosition 전용
---
bool success
string message
